Navbar component done and made responsive
Nikhilkumar055/Trialhub pull request #3
Opened 2022-12-29 11:58 UTC by shazebK

I have created the navbar component which is responsive for mobile devices 
Please review and merge this PR.
![Screenshot (91)](https://user-images.githubusercontent.com/106864146/209948023-c4b34b38-5749-494d-9839-cdbedd0e6e66.png)
![Screenshot (92)](https://user-images.githubusercontent.com/106864146/209948029-8719d52e-f1fe-40be-a5f2-598b852812ec.png)

2023-01-03 16:22 UTC, arpitverma9335 requested changes
Please have a look at the comments

2023-01-03 16:22 UTC, arpitverma9335 commented on styles/globals.css
> +  object-fit: cover;
why have you given width and height when you have given object-fit as cover??

2023-01-03 16:22 UTC, arpitverma9335 commented on pages/components/sidebar.tsx
> -                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.
why are these changes, can you explain?

2023-01-07 08:52 UTC, shazebK commented on styles/globals.css
> +  object-fit: cover;
because width of the td tag would distort the image.

2023-01-08 15:13 UTC, arpitverma9335 commented on pages/components/sidebar.tsx
> -                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.
why these changes??

Please reply on all comments.

2023-01-08 16:24 UTC, shazebK commented on pages/components/sidebar.tsx
> -                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.
Sorry for replying late

I have used Camel casing in attributes because in Console it was giving errors for these attributes.

I just tried to rectify those problems so that it don't code don't give any errors
😅

2023-01-08 16:32 UTC, shazebK commented on pages/employee.tsx
> +import GridIcon from './components/icons/GridIcon'
@arpitverma9335
I probably did'nt noticed this while making this change , and also don't remember why I did it. 
But I guess as all other icons file started with Capital letter I might have mistaken it due to this reason .

2023-01-12 15:16 UTC, closed without merging